#Pakistan Flag:
import turtle as t
t.speed(8)
t.pensize(3)
t.bgcolor("pink")
t.fillcolor("red")
t.begin_fill()

def rectangle_shape(color,width,height):
    t.fillcolor(color)
    t.begin_fill()
    for i in range(2):
        t.forward(width)
        t.left(90)
        t.forward(height)
        t.left(90)
    t.end_fill()

rectangle_shape('white',200,400)
t.penup()
t.goto(200,0)
t.pendown()
rectangle_shape('green',400,400)

t.penup()
t.goto(300,280)
t.pendown()
t.fillcolor('white')
t.begin_fill()
t.right(130)
t.circle(100,extent = 200)
t.penup()
t.goto(300,280)
t.pendown()
t.right(180)
t.circle(100,extent = 160)
t.end_fill()
t.penup()
t.goto(450,260)
t.left(45)
t.pendown()
t.fillcolor('white')
t.begin_fill()
for i in range(6):
    t.left(72)
    t.fd(15)
    t.rt(144)
    t.fd(15)
t.end_fill()
t.penup()
t.home()
t.pendown()
t.done()